name = "flow-worker"
main = "build/worker/shim.mjs"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[build]
command = "cargo install -q worker-build && worker-build --release"

[ai]
binding = "AI"

[vars]
TRANSCRIPTION_PROVIDER = "cloudflare"

[observability]
[observability.logs]
enabled = true
invocation_logs = true